services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: healthcare_postgres
    environment:
      POSTGRES_DB: healthcare_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - healthcare_network

  # Python Backend
  backend:
    build: ./backend
    container_name: healthcare_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/healthcare_portal
      SECRET_KEY: your-super-secret-key-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - healthcare_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build: ./frontend
    container_name: healthcare_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - healthcare_network
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  postgres_data:

networks:
  healthcare_network:
    driver: bridge
