# docker-compose.dev.yml
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: taskmanager_postgres_dev
    environment:
      POSTGRES_DB: taskmanager_dev
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - taskmanager_dev_network

  redis:
    image: redis:7-alpine
    container_name: taskmanager_redis_dev
    ports:
      - "6379:6379"
    networks:
      - taskmanager_dev_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: taskmanager_backend_dev
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://taskuser:taskpass123@postgres:5432/taskmanager_dev
      - SECRET_KEY=dev-secret-key
      - DEBUG=True
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - taskmanager_dev_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_dev_data:

networks:
  taskmanager_dev_network:
    driver: bridge
