# Monitoring configuration (monitoring/prometheus.yml)
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ai-agent-builder'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:5432']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
