version: '3.8'

services:
  # PostgreSQL Database for Claims Service (Enhanced)
  claims-db:
    image: postgres:17-alpine
    container_name: claims-integrated-db
    environment:
      POSTGRES_DB: fhir_claims_db
      POSTGRES_USER: fhir_user
      POSTGRES_PASSWORD: fhir_password_2024!
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - claims_postgres_data:/var/lib/postgresql/data
      - ../../../../HealthcareFoundation/CoreServices/Claims/database/init_enhanced.sql:/docker-entrypoint-initdb.d/init_enhanced.sql:ro
    ports:
      - "5435:5432"  # Changed from 5432 to avoid conflicts
    networks:
      - claims-integrated-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fhir_user -d fhir_claims_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Claims Service Backend (Enhanced with DenialPrediction integration)
  claims-service:
    build:
      context: ../../../../HealthcareFoundation/CoreServices/Claims
      dockerfile: backend/Dockerfile
    container_name: claims-service-backend
    environment:
      DATABASE_URL: postgresql://fhir_user:fhir_password_2024!@claims-db:5432/fhir_claims_db
      DATABASE_HOST: claims-db
      DATABASE_PORT: 5432
      SECRET_KEY: your-super-secret-key-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      CORS_ORIGINS: "http://localhost:3002,http://localhost:3003,http://denial-prediction-frontend"
      LOG_LEVEL: info
      ENVIRONMENT: development
    volumes:
      - ../../../../HealthcareFoundation/CoreServices/Claims:/app:ro
      - claims_service_logs:/app/logs
    ports:
      - "8002:8000"  # Changed from 8001:8000 to avoid conflicts
    networks:
      - claims-integrated-network
    depends_on:
      claims-db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # DenialPrediction API (Enhanced with Claims Service integration)
  denial-prediction-api:
    build: .
    container_name: denial-prediction-api
    ports:
      - "8003:8000"  # Changed from 8000:8000 to avoid conflicts
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - CLAIMS_SERVICE_URL=http://claims-service:8000  # Internal service communication
      - CLAIMS_SERVICE_BASE_URL=http://localhost:8002  # External access
    restart: unless-stopped
    depends_on:
      - claims-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - claims-integrated-network

  # Claims Service Frontend
  claims-service-frontend:
    build:
      context: ../../../../HealthcareFoundation/CoreServices/Claims/frontend
      dockerfile: Dockerfile
    container_name: claims-service-frontend
    environment:
      REACT_APP_API_URL: http://localhost:8002
      REACT_APP_ENVIRONMENT: development
      REACT_APP_VERSION: 1.0.0
    ports:
      - "3002:80"  # Changed from 3000:80 to avoid conflicts
    networks:
      - claims-integrated-network
    depends_on:
      - claims-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # DenialPrediction Frontend (if available)
  denial-prediction-frontend:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: denial-prediction-frontend
    ports:
      - "3003:8501"  # Streamlit default port
    environment:
      - DENIAL_PREDICTION_API_URL=http://localhost:8003
      - CLAIMS_SERVICE_URL=http://localhost:8002
    volumes:
      - ./dashboard:/app
    depends_on:
      - denial-prediction-api
    restart: unless-stopped
    networks:
      - claims-integrated-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: claims-integrated-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - claims-integrated-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # MLflow for model tracking (optional)
  mlflow:
    image: python:3.9-slim
    container_name: claims-integrated-mlflow
    command: >
      sh -c "pip install mlflow psycopg2-binary &&
             mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql://fhir_user:fhir_password_2024!@claims-db:5432/fhir_claims_db"
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    depends_on:
      - claims-db
    networks:
      - claims-integrated-network
    restart: unless-stopped

networks:
  claims-integrated-network:
    driver: bridge

volumes:
  claims_postgres_data:
  claims_service_logs:
  redis_data: 