# docker-compose.yml

services:
  postgres:
    image: postgres:15
    container_name: activity_log_db
    environment:
      POSTGRES_DB: activity_log_db
      POSTGRES_USER: activity_user
      POSTGRES_PASSWORD: activity_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: activity_log_backend
    environment:
      DATABASE_URL: postgresql://activity_user:activity_password@postgres:5432/activity_log_db
      SECRET_KEY: your-super-secret-key-change-in-production
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: activity_log_frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api

volumes:
  postgres_data:
